from dataclasses import dataclass
from enum import Enum
import json
import datetime


@dataclass(frozen=True)
class BuildRef:
    """
    Reference to a build triggered by a wehbook event.

    Attributes:
        repo (str): The repository's full_name field from the webhook payload.
                    (e.g., "owner/repo")
        ref (str):  The git reference of the commit to build (e.g., "refs/heads/main" or "refs/tags/v1.0").
                    Losely equivalent to what branch the event was triggered on.
        sha (str):  The full commit SHA of the commit to build.
        installation_id (Optional[int]): The GitHub App installation ID if the event was triggered by a
                        GitHub App installation.

    Source: https://gist.github.com/walkingtospace/0dcfe43116ca6481f129cdaa0e112dc4
    Note:   The github documentation does not specify the exact format of the repository
            field, and hence how the repo field is derived should be clarified.
    """

    repo: str
    ref: str
    sha: str
    installation_id: int | None = None

    @property
    def branch(self) -> str:
        """
        Extracts the branch name from the ref field.
        For example, if ref is "refs/heads/main", this will return "main".
        If ref is "refs/tags/v1.0", this will return "v1.0".
        Returns:
            str: The extracted branch or tag name.
        """
        return self.ref.removeprefix("refs/heads/")

    @property
    def ssh_url(self) -> str:
        """
        Constructs the SSH URL for the repository based on the repo field.
        For example, if repo is "owner/repo", this will return
        "git@github.com:owner/repo.git".
        """
        return f"git@github.com:{self.repo}.git"

    @property
    def clone_url(self) -> str:
        """HTTPS URL FOR CLONING REPO"""
        return f"https://github.com/{self.repo}.git"


class BuildStatus(str, Enum):
    """
    Enumeration of possible build statuses.
    """

    SUCCESS = "success"
    FAILURE = "failure"
    PENDING = "pending"
    ERROR = "error"


@dataclass(frozen=True)
class BuildReport:
    """
    Report indicating the status of a build to be sent back to the user.

    Attributes:
        state (BuildStatus): The status of the build (e.g., success, failure, pending, error).
        target_url (Optional[str]): An optional URL pointing to the build logs or details.
        description (Optional[str]): An optional description providing more context about the build status.
        context (str): A string label to differentiate this status from others (default: "Group 10 CI/CD Pipeline").
    """

    state: BuildStatus
    target_url: str | None = None
    description: str | None = None
    context: str = "Group 10 CI/CD Pipeline"


class LogType(str, Enum):
    """Types of entries in the build history."""

    INFO = "INFO"
    ERROR = "ERROR"
    WARNING = "WARNING"


@dataclass
class LogEntry:
    """Detailed record of a CI build execution and its outcome.

    This class serves as the primary data structure for persistent storage of
    build history. It encapsulates both the metadata of the trigger event
    (repo, commit, time) and the results of the build process (status, logs).

    Attributes:
        type (LogType): Categorization of the log (e.g., INFO, ERROR).
        repo_url (str): The full clone URL of the GitHub repository.
        refspec (str): The git reference that triggered the build
            (e.g., 'refs/heads/main').
        commit_SHA (str): The unique 40-character identifier of the commit.
        date_time (datetime): The timestamp when the build was processed.
        status (BuildStatus): The final outcome of the build (SUCCESS, FAILURE, etc.).
        gradle_output (str): The raw console output/logs generated by the
            Gradle build/test process.
    """

    type: LogType
    repo_url: str
    refspec: str
    commit_SHA: str
    date_time: datetime
    status: BuildStatus
    gradle_output: str

    def generate_log_file_name(self) -> str:
        """Generates a unique filename for storing raw logs on disk.

        Uses the commit SHA and log type to ensure that multiple builds of
        different commits do not overwrite each other's log files.

        Returns:
            str: A filename in the format '{sha}_{type}.log'.
        """
        return f"{self.commit_SHA}_{self.type.value}.log"

    def __str__(self) -> str:
        """Serializes the log entry into a JSON-formatted string.

        This method is particularly useful for storing the entire entry as
        a text blob in a database or sending it over an HTTP response.

        Returns:
            str: A JSON string representation of the object, with the
                timestamp converted to Unix milliseconds.
        """
        json_object = {
            "type": self.type.value,
            "repo_url": self.repo_url,
            "refspec": self.refspec,
            "commit_SHA": self.commit_SHA,
            "date_time": int(self.date_time.timestamp() * 1000),
            "status": self.status.value,
            "gradle_output": self.gradle_output,
        }

        return json.dumps(json_object)
